FROM python:3.11

# set working directory
WORKDIR /nacaTransformer

# copy contents from src to workdir
COPY airfoilMNIST/ ./airfoilMNIST
COPY requirements.txt ./

# install GPU-version of JAX and FLAX
RUN pip install --upgrade "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
RUN pip install flax
RUN pip install optax
RUN pip install -q clu
RUN pip install tensorflow-datasets
RUN pip install -U matplotlib

RUN pip install -r requirements.txt
